# Generated by Django 2.2 on 2021-08-27 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import users.models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('', 'Género'), ('undefined', 'Sin definir'), ('male', 'Masculino'), ('female', 'Femenino')], max_length=25, null=True, verbose_name='Género')),
                ('profile_picture', sorl.thumbnail.fields.ImageField(blank=True, max_length=500, null=True, upload_to=users.models._picture_path, validators=[utils.models.validate_profile_picture_size], verbose_name='Imagen de perfil')),
                ('cui', models.CharField(blank=True, max_length=100, null=True, verbose_name='CUI')),
                ('has_limited_access', models.BooleanField(default=False, verbose_name='Accesso limitado')),
                ('dont_expire_session', models.BooleanField(default=True, verbose_name='Expirar sesión')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(error_messages={'required': 'Este campo es requerido ', 'unique': 'Un usuario con este correo ya existe'}, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Esta activo?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='¿Es un Administrador?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es un Staff?')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Phone', verbose_name='Teléfono')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PasswordRetrievalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, verbose_name='Token')),
                ('is_consumed', models.BooleanField(default=False, verbose_name='¿Está consumido?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de recuperación de password',
                'verbose_name_plural': 'Eventos de recuperación de password',
                'db_table': 'users_password_retrieval_event',
            },
        ),
    ]
