# Generated by Django 2.2 on 2021-08-27 23:33

import companies.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(error_messages={'required': 'Este campo es requerido', 'unique': 'Un compañia con este nombre ya existe'}, max_length=80, unique=True, verbose_name='Nombre')),
                ('email', models.EmailField(error_messages={'required': 'Este campo es requerido', 'unique': 'Un usuario con este correo ya existe'}, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('facebook', models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, default='', max_length=100, verbose_name='Twitter')),
                ('web_page', models.CharField(blank=True, default='', max_length=100, verbose_name='Sitio Web')),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, max_length=500, null=True, upload_to=companies.models._picture_path_company, validators=[utils.models.validate_profile_picture_size], verbose_name='Logo')),
                ('has_marketing', models.BooleanField(default=False, verbose_name='¿Tiene marketing?')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Address', verbose_name='Dirección')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Phone', verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
            },
        ),
    ]
