# Generated by Django 2.2 on 2021-08-28 00:03

from django.db import migrations, models
import django.db.models.deletion
import services.models
import sorl.thumbnail.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre de imagenes')),
                ('picture1', sorl.thumbnail.fields.ImageField(blank=True, max_length=500, null=True, upload_to=services.models._picture_path_service, validators=[utils.models.validate_profile_picture_size], verbose_name='Imagen 1')),
                ('picture2', sorl.thumbnail.fields.ImageField(blank=True, max_length=500, null=True, upload_to=services.models._picture_path_service, validators=[utils.models.validate_profile_picture_size], verbose_name='Imagen 2')),
                ('picture3', sorl.thumbnail.fields.ImageField(blank=True, max_length=500, null=True, upload_to=services.models._picture_path_service, validators=[utils.models.validate_profile_picture_size], verbose_name='Imagen 3')),
                ('picture4', sorl.thumbnail.fields.ImageField(blank=True, max_length=500, null=True, upload_to=services.models._picture_path_service, validators=[utils.models.validate_profile_picture_size], verbose_name='Imagen 4')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿Esta activo?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.FloatField(validators=[services.models.validate_interval], verbose_name='Precio')),
                ('promotion_percentage', models.FloatField(validators=[services.models.validate_interval], verbose_name='Porcentaje de promoción')),
                ('has_offer', models.BooleanField(default=False, verbose_name='¿Tiene oferta?')),
                ('url', models.CharField(blank=True, default='', max_length=100, verbose_name='Sitio Web')),
                ('pictures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Picture', verbose_name='Imagenes')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Descripción de servicio',
                'verbose_name_plural': 'Descripción de servicios',
            },
        ),
    ]
